#!/bin/bash

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

DPKG_ADMIN_DIR="/var/lib/snapd/hostfs/var/lib/dpkg/"
# snap list
if [[ -f "${DPKG_ADMIN_DIR}status" ]] && [[ -x "$(command -v $SNAP/usr/bin/dpkg-query --version)" ]]; then
    $SNAP/usr/bin/dpkg-query --show --admindir="${DPKG_ADMIN_DIR}"
fi

SNAP_ROOT_DIR="/var/lib/snapd/hostfs/"
if [[ -d "${SNAP_ROOT_DIR}" ]] && [[ -x "$(command -v $SNAP/usr/bin/list-snaps.py --help)" ]]; then
    $SNAP/usr/bin/list-snaps.py --rootdir="${SNAP_ROOT_DIR}"
fi
