#!/bin/bash

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# snap list
if [[ -f "/var/lib/snapd/hostfs/var/lib/dpkg/status" ]] && [[ -x "$(command -v $SNAP/usr/bin/dpkg-query --version)" ]]; then
    $SNAP/usr/bin/dpkg-query --show --admindir=/var/lib/snapd/hostfs/var/lib/dpkg/
fi

if [ -x "$(command -v $SNAP/usr/bin/snap --version)" ]; then
  $SNAP/usr/bin/snap list | $SNAP/usr/bin/tail -n +2 | while read -r snap_name snap_version snap_revision snap_channel snap_publisher snap_notes
  do
      parsed_snap_channel=${snap_channel#"latest/"}
      parsed_snap_channel=${parsed_snap_channel%"/…"}
      echo -e "snap:${snap_name}\t${parsed_snap_channel}\t${snap_revision}"
  done
fi
